M48
; DRILL file {KiCad 7.0.5-0} date 2024 March 10, Sunday 13:53:24
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-10T13:53:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
%
G90
G05
T2
X-1.5331Y2.2126
T1
G00X-1.5331Y1.9256
M15
G01X-1.5331Y1.909
M16
G05
T0
M30
