M48
; DRILL file {KiCad 8.0.2-1} date 2024-05-26T22:58:53-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-26T22:58:53-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
%
G90
G05
T2
X-1.447Y2.1496
T1
G00X-1.7341Y2.1496
M15
G01X-1.7506Y2.1496
M16
G05
M30
